# 容器 配置
server:
  port: 8448      # https 端口号，正式 443；测试 8443
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

# 数据库 及 Redis 配置    
spring:
# disable caching for Thymeleaf so that we can make changes on the fly
  thymeleaf:
    cache: false
  redis:
    host: localhost
    password:
#  使用 MySQL 不用做任何修改
  datasource:
    url: jdbc:mysql://localhost:3306/any_db?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    sql-script-encoding: utf-8
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10

# Mybatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true    # 驼峰命名转换
